### PR TITLE
[Chore] Fix valid hostname format

### PR DESCRIPTION
**Pull request by ndemianc**
### What is a problem:

`JSONSchemer.schema` treats  strings which starts with digit `1drv.ms` with `hostname` format as invalid:

### Example
```
require 'json_schemer'

schema = {"type"=>"object", "properties"=>{"abc"=>{"type"=>"string", "format" => "hostname", "minimum"=>11}}}

schemer = JSONSchemer.schema(schema)

schemer.valid?({ 'abc' => "1drv.ms" })
```

### Output:

`=> false`

After the fix:

```
schemer.valid?({ 'abc' => "1drv.ms" }) # => true
```

### What is a solution:

- [x] Adjust `LABEL_REGEX_STRING` which used for `HOSTNAME_REGEX`
- [x] Add unit tests

### CODE REVIEW

**Comment by Kmalynss** [comment]
+1

**Comment by lszyn** [comment]
+1

**Comment by ndemianc** [comment]
@davishmcclurg Can You please take a look at it?

**Review by davishmcclurg — APPROVED** [review]
Looks great—thanks!

For reference:

https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.7.3.3

> hostname:
As defined by RFC 1123, section 2.1, including host names produced using the Punycode algorithm specified in RFC 5891, section 4.4.

https://tools.ietf.org/html/rfc1123#section-2

> The syntax of a legal Internet host name was specified in RFC-952
[DNS:4].  One aspect of host name syntax is hereby changed: the
restriction on the first character is relaxed to allow either a
letter or a digit.

https://tools.ietf.org/html/rfc952

```
<hname> ::= <name>*["."<name>]
<name>  ::= <let>[*[<let-or-digit-or-hyphen>]<let-or-digit>]
```

**Comment by davishmcclurg** [comment]
Released in 0.2.15

**Comment by ndemianc** [comment]
@davishmcclurg Thanks! 👍

**Pull request merged**
